### ISSUE TITLE
App force stops whenever i try playing any song.

### ISSUE THREAD

**Issue by realrufans** [n76/Symphony#17]
### Screenshots
<div class="pull-left">
<p>

![Screenshot_20190104-110429.png](https://ipfs.busy.org/ipfs/QmTDUzJqNBESm7j7NPHmFSDeyAvhcsUcRHFxhM4kdec7sA)

</p>
</div>

<div class="pull-right">
<p>

![Screenshot_20190104-110445.png](https://ipfs.busy.org/ipfs/QmRL8VdLgoXvQzKUhRwpPFCt7wTi4Kv5XbMERLycWULM6d)

</p>
</div>
<hr>

### Device info

![Screenshot_20190104-110740.png](https://ipfs.busy.org/ipfs/QmeMmeYpCjhn4Kbkyy68PQd3GxVwCpQ4uEwvR7eFFVkMZp)

**Comment by n76** [comment]
I cannot duplicate this problem, can you get me the output of "adb logcat" showing the force close? With that I might be able to figure out what the problem is.

Also, does this happen on every song or just on one song? If on every song it might be an Android O change. If on one song, it might be something in the song file.

**Comment by realrufans** [comment]
I happens to any song I pick.

And how do I get the adb logcat ? My device isn't rooted.

**Comment by n76** [comment]
Sorry for my tardy response: I did not notice you had replied to my request for additional information.

To get a logcat:
- Enable developer mode, then within developer options enable "Android debugging".
- On you desktop/laptop computer, install Android Debug Bridge (ADB).
- Plug your phone into your computer and type "adb logcat" in a terminal window.

Since it is happening on every song and since the song names, performers and album artwork are showing, I suspect this is a permissions issue. The name, performers, etc. are gotten via calls to the Android media manager. The album art is also acquired that way but by a different API. Actually playing the track requires that Symphony can read the track file so the permissions on storage access matter for that.

**Comment by n76** [comment]
Odd thing on the screen shot of Symphony you posted: The player controls at the bottom don't look like a track has been picked. Even on a clean install (or with app data cleared) Symphony should have selected a (default) track to display data for. I suspect that tapping play on the player will cause issues because of that. If you tap on a track title above the player controls does it still crash?

**Comment by realrufans** [comment]
It played now then crashed ..

I will make a gif soon

**Comment by realrufans** [comment]
https://youtu.be/xHS7pR-HXUo

**Comment by n76** [comment]
Definitely crashing, but unless I can somehow get a trace of the crash I'll not be able to fix it.

**Comment by realrufans** [comment]
i will provide you with the logcat.

**Comment by ergodaveh** [comment]
I have recently built the latest version on my Android 9 with One UI version 1.0 and the app crashes on selecting a Song with this error message

V/MediaPlayer-JNI: getDuration: 191242 (msec)
V/MediaPlayer-JNI: getCurrentPosition: 0 (msec)
D/AndroidRuntime: Shutting down VM
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.fitchfamily.android.symphony, PID: 23594
                  android.app.RemoteServiceException: Bad notification for startForeground: java.lang.RuntimeException: invalid channel for service notification: Notification(channel=null pri=0 contentView=null vibrate=null sound=null tick defaults=0x0 flags=0x42 color=0x00000000 vis=PRIVATE semFlags=0x0 semPriority=0 semMissedCount=0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1872)
                      at android.os.Handler.dispatchMessage(Handler.java:106)
                      at android.os.Looper.loop(Looper.java:214)
                      at android.app.ActivityThread.main(ActivityThread.java:7045)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:964)
V/MediaPlayerNative: message received msg=211, ext1=0, ext2=0
                     unrecognized message: (211, 0, 0)
                     callback application
                     back from callback
I/Process: Sending signal. PID: 23594 SIG: 9
Disconnected from the target VM, address: 'localhost:8613', transport: 'socket'

**Comment by realrufans** [comment]
Thanks

**Comment by realrufans** [comment]
Thanks for this . I have been looking for ways to make one.

**Comment by n76** [comment]
Sorry it has taken me this long to get back. . . Looks like the API for notifications has changed and I need to detect if the app is running on 8.1 or higher and if so create a unique channel ID.

Unfortunately, I am having difficulty getting to developer.android.com to read up on the changes and won't have time to get to this again for a couple more days.

Since I don't have a phone that runs that new a version of Android, I am hoping that one of you can do some testing for me, probably sometime next week. Thanks1

**Comment by ergodaveh** [comment]
No worries I can contribute a revised method. I will request a pull or would you prefer something in the comments.
Cheers

**Comment by n76** [comment]
> No worries I can contribute a revised method. I will request a pull or would you prefer something in the comments.
> Cheers

If you have the time to contribute a revised method, I would accept a pull request. Thanks1

**Comment by n76** [comment]
@realrufans and @ergodaveh - I think I have this fixed. Please re-open this issue or create a new one if you are still having problems.

**Comment by realrufans** [comment]
@n76 Works fine now. Thank you for this simple app.
